language: java

jdk: openjdk11

dist: xenial

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
